name: Deploy to AWS Amplify (API Method)

on:
  push:
    branches: [master, main]
  workflow_dispatch:

env:
  NODE_VERSION: "18"
  AWS_REGION: "us-east-1"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v4

      - name: 🏗️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔨 Build Next.js app
        run: npm run build

      - name: 🔧 Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 📤 Create deployment archive
        run: |
          echo "Creating deployment archive..."
          # Exclude node_modules and other unnecessary files
          zip -r deployment.zip . -x "node_modules/*" ".git/*" ".github/*" "*.md" ".env*"

      - name: 🚀 Deploy to AWS Amplify via API
        run: |
          echo "Starting deployment to AWS Amplify..."
          
          # Start a new job
          JOB_ID=$(aws amplify start-job \
            --app-id ${{ secrets.AMPLIFY_APP_ID }} \
            --branch-name ${{ secrets.AMPLIFY_BRANCH_NAME }} \
            --job-type RELEASE \
            --query 'jobSummary.jobId' \
            --output text)
          
          echo "Job ID: $JOB_ID"
          
          # Wait for deployment to complete
          echo "Waiting for deployment to complete..."
          aws amplify wait job-succeeded \
            --app-id ${{ secrets.AMPLIFY_APP_ID }} \
            --branch-name ${{ secrets.AMPLIFY_BRANCH_NAME }} \
            --job-id $JOB_ID || {
              echo "Deployment failed. Getting job details..."
              aws amplify get-job \
                --app-id ${{ secrets.AMPLIFY_APP_ID }} \
                --branch-name ${{ secrets.AMPLIFY_BRANCH_NAME }} \
                --job-id $JOB_ID
              exit 1
            }
          
          echo "Getting final deployment info..."
          aws amplify get-app --app-id ${{ secrets.AMPLIFY_APP_ID }}

      - name: 📊 Get app URL
        run: |
          APP_URL=$(aws amplify get-app \
            --app-id ${{ secrets.AMPLIFY_APP_ID }} \
            --query 'app.defaultDomain' \
            --output text)
          echo "🌐 App URL: https://${{ secrets.AMPLIFY_BRANCH_NAME }}.$APP_URL"

      - name: ✅ Deployment complete
        run: |
          echo "🎉 AWS Amplify deployment completed successfully!"
          echo "🌐 Your Did Lions Win app is now live!"
          echo "⚡ Next.js app deployed to AWS Amplify with CDN"
